packages:
  - grafana-plugin
  - packages/*
catalogs:
  react18or19:
    "@types/react": ^18.3.28 || ^19.2.14
    "@types/react-dom": ^18.3.7 || ^19.2.3
    react: ^18.3.1 || ^19.2.6
    react-dom: ^18.3.1 || ^19.2.6
  react18:
    "@types/react": ^18.3.28
    "@types/react-dom": ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1
catalog:
  "@babel/core": ^7.29.0
  "@carbon/icons-react": ^11.81.0
  "@carbon/react": ^1.108.0
  "@carbon/styles": ^1.107.0
  "@carbon/themes": ^11.74.0
  "@emotion/css": ^11.13.5
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.1
  "@eslint/js": ^10.0.1
  "@eslint/compat": ^2.0.3
  "@grafana/data": ^13.1.0-25893932881
  "@grafana/runtime": ^13.1.0-25893932881
  "@grafana/schema": ^13.0.1
  "@grafana/tsconfig": ^2.1.0
  "@grafana/ui": ^13.1.0-25893932881
  "@swc/core": ^1.15.33
  "@swc/helpers": ^0.5.21
  "@swc/jest": ^0.2.39
  "@swc/plugin-emotion": ^14.9.0
  "@tailwindcss/vite": ^4.3.0
  "@tanstack/react-query": ^5.100.10
  "@tanstack/react-query-devtools": ^5.100.10
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@types/glob": ^9.0.0
  "@types/jest": ^30.0.0
  "@types/lodash": ^4.17.24
  "@types/node": ^25.8.0
  "@types/react-router-dom": ^5.3.3
  "@vitejs/plugin-react-swc": ^4.3.1
  copy-webpack-plugin: ^14.0.0
  css-loader: ^7.1.4
  dotenv-cli: ^11.0.0
  eslint: ^10.4.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsdoc: ^62.9.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.1.1
  eslint-webpack-plugin: ^6.0.0
  fork-ts-checker-webpack-plugin: ^9.1.0
  glob: ^13.0.6
  globals: ^17.6.0
  identity-obj-proxy: ^3.0.0
  imports-loader: ^5.0.0
  jest: ^30.4.2
  jest-environment-jsdom: ^30.4.1
  lodash: ^4.18.1
  prettier: ^3.8.3
  prettier-plugin-tailwindcss: ^0.8.0
  replace-in-file-webpack-plugin: ^1.0.6
  rxjs: ^7.8.2
  sass: ^1.99.0
  sass-loader: ^16.0.8
  style-loader: ^4.0.0
  swc-loader: ^0.2.7
  tailwindcss: ^4.3.0
  terser-webpack-plugin: ^5.6.0
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tslib: ^2.8.1
  typescript: ^6.0.3
  typescript-eslint: ^8.59.3
  vite: ^8.0.13
  vite-plugin-dts: ^5.0.0
  vite-plugin-svgr: ^5.2.0
  webpack: ^5.106.2
  webpack-cli: ^7.0.2
  webpack-livereload-plugin: ^3.0.2
  webpack-subresource-integrity: ^5.2.0-rc.1
  webpack-virtual-modules: ^0.6.2
