/**
 * SelfSignedCertificate component - inlined from @grafana/plugin-ui v0.10.10
 * Source: https://unpkg.com/@grafana/plugin-ui@0.10.10/dist/esm/components/ConfigEditor/Auth/tls/SelfSignedCertificate.js
 * License: Apache-2.0
 */

import { cx } from '@emotion/css';
import { InlineField, SecretTextArea } from '@grafana/ui';
import React from 'react';

import { useCommonStyles } from './auth-styles';
import { TLSSettingsSection } from './TLSSettingsSection';

// No-op function for readOnly mode to satisfy TypeScript and ESLint
const noop = () => {
  // Intentionally empty - used to disable functionality in readOnly mode
};

interface SelfSignedCertificateProps {
  enabled: boolean;
  certificateConfigured: boolean;
  onToggle: (enabled: boolean) => void;
  onCertificateChange: (certificate: string) => void;
  onCertificateReset: () => void;
  tooltips?: {
    certificateLabel?: string;
  };
  readOnly?: boolean;
}

export const SelfSignedCertificate = ({
  enabled,
  certificateConfigured,
  onToggle,
  onCertificateChange,
  onCertificateReset,
  tooltips,
  readOnly,
}: SelfSignedCertificateProps) => {
  const commonStyles = useCommonStyles();

  return (
    <TLSSettingsSection
      enabled={enabled}
      label="Add self-signed certificate"
      tooltipText="Add your own Certificate Authority (CA) certificate on top of one generated by the certificate authorities for additional security measures"
      onToggle={(newEnabled) => onToggle(newEnabled)}
      readOnly={readOnly}
    >
      <InlineField
        label="CA Certificate"
        labelWidth={24}
        tooltip={tooltips?.certificateLabel ?? 'Your self-signed certificate'}
        required={true}
        htmlFor="self-signed-certificate-input"
        interactive={true}
        grow={true}
        className={cx(commonStyles.inlineFieldNoMarginRight, commonStyles.inlineFieldWithSecret)}
        disabled={readOnly}
      >
        <SecretTextArea
          id="self-signed-certificate-input"
          isConfigured={certificateConfigured}
          onChange={(e) => onCertificateChange(e.currentTarget.value)}
          onReset={readOnly ? noop : onCertificateReset}
          placeholder="Begins with --- BEGIN CERTIFICATE ---"
          rows={6}
          required={true}
        />
      </InlineField>
    </TLSSettingsSection>
  );
};
